### ISSUE TITLE
[feat] Add `--wrap n` option to change the length at which lines get wrapped

### ISSUE THREAD

**Issue by cdesaintguilhem** [WGUNDERWOOD/tex-fmt#38] opened 2024-10-09 07:55 UTC
It could be nice to let the user choose the length at which lines get wrapped, with the default remaining 80 as it is now, and `--wrap 0` being the equivalent of `--keep`.

**Comment by WGUNDERWOOD** [comment] 2024-10-09 09:28
Implemented in a6177f0cd099ec322ea9349377e6fe65de7b9126, let me know if it works as expected. Thanks for your helpful suggestions!

**Comment by cdesaintguilhem** [comment] 2024-10-09 10:01
It works as expected! (Including with the recent ability to customise parameters to `tex-fmt` inside LaTeX-Workshop on VS Code, see [this PR](https://github.com/James-Yu/LaTeX-Workshop/pull/4427))

Thanks for implementing this so quickly!

It doesn't wrap as tightly to the 120-character rule as the [Rewrap](https://github.com/stkb/Rewrap) extension for VS Code, but that's maybe due to the minimum line length setting. And I understand that you're using the `-10` offset to have some margin when wrapped lines need indenting after wrapping, and changing that might require something like multiple passes over the same block of lines and could introduce further bugs.

**Comment by WGUNDERWOOD** [comment] 2024-10-09 10:05
That's right, see #6 for a discussion of this.

**Comment by cdesaintguilhem** [comment] 2024-10-09 10:53
I wonder if there could be a dynamic "minimum length" which takes into account the current indent of the line that is being wrapped... I'll have a think to see if I can come up with a working idea.

Maintaining `--keep` makes sense to me.

**Comment by WGUNDERWOOD** [comment] 2024-10-09 11:06
The problem is that where you choose to wrap the line also affects the indentation level (you might wrap it before a closing bracket, for example).

**Comment by cdesaintguilhem** [comment] 2024-10-09 11:45
Ah yes indeed. One (not so nice) solution would be to do several local iterations. (I say this without knowing how the initial multi-pass framework was implemented.) 

My thought is: when a line should be wrapped, split it into several lines and queue them all for re-indentation. As the code iterates through the queued lines, it corrects the indentation if need be, and if that requires wrapping again, then it merges the trailing word(s) with the next line on the queue (if there is one), computes the new wrapping point, and submits the remaining line for re-indentation (if there is one). This feels like it should converge to a stable combination of indentation and tight wrapping, but feeling never takes care of all the edge cases.

**Closed** 2024-10-10 15:41 UTC
