### ISSUE TITLE
[question] wrapping long lines

### ISSUE THREAD

**Issue by marcfranquesa** [WGUNDERWOOD/tex-fmt#49] opened 2024-10-24 09:30 UTC
I noticed when formatting a file containing:

```latex
\usetikzlibrary{calc, graphs, graphs.standard, shapes, arrows, positioning, decorations.pathreplacing, decorations.markings, decorations.pathmorphing, fit, matrix, patterns, shapes.misc, tikzmark}
```

It gets formatted to:
```latex
\usetikzlibrary{calc, graphs, graphs.standard, shapes, arrows,
    positioning, decorations.pathreplacing, decorations.markings,
decorations.pathmorphing, fit, matrix, patterns, shapes.misc, tikzmark}
```

Wrapped into 3 lines where only the second is indented. Is this the desired output?

**Comment by WGUNDERWOOD** [comment] 2024-10-24 09:33
This is a duplicate of #32. This is currently the desired behaviour, but if there is interest in adding a flag to change this, I could look into it. Could you clarify what you would prefer here?

**Comment by marcfranquesa** [comment] 2024-10-24 09:44
Ah, my bad. In this case, and similar to a long `\usepackage` I would prefer to have each library in a separate line,

```latex
\usetikzlibrary{
    calc,
    graphs,
    graphs.standard,
    shapes,
    arrows,
    ...
```

However in the example provided in #32, I would prefer the last alternative proposed.

```latex
\comment{
  This is a comment
  that the user has decided
  to write on different lines.
}
```

This is just my wishlist, I currently do not know how hard it would be to differentiate the two cases. I guess it would have to be a list of specific commands like `usepackage` where the behaviour would be like in the first case, and otherwise like the second.

**Comment by marcfranquesa** [comment] 2024-10-24 09:47
Just read the comments on adding extra line breaks, in that case,

```latex
\usetikzlibrary{
  calc,
  graphs,
  graphs.standard,
  shapes,
  arrows,
  ...}
```

and

```latex
\comment{
  This is a comment
  that the user has decided
  to write on different lines.}
```

**Comment by cdesaintguilhem** [comment] 2024-10-24 10:53
@marcfranquesa Could you add a 👍 on [this comment](https://github.com/WGUNDERWOOD/tex-fmt/issues/32#issuecomment-2393046635) so that there can be a tally of how desirable this feature this?

**Closed** 2024-10-24 12:30 UTC
